//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceUMS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://onebank.com.bd/", ConfigurationName="ServiceReferenceUMS.OBLAPPSoap")]
    public interface OBLAPPSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetAllUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetAllUserResponseGetAllUserResult> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetEmployeeNameBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetEmployeeNameByAsync(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetIDbyEmployeeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> GetIDbyEmployeeIdAsync(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetPreDeptNameBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetPreDeptNameByAsync(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetPreDeptIdBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetPreDeptIdByAsync(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetPreBranchIdBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetPreBranchIdByAsync(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetPreDesigBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetPreDesigByAsync(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetGlobalEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetGlobalEnumResponseGetGlobalEnumResult> GetGlobalEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetDeptNameByDeptId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDeptNameByDeptIdAsync(int DeptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetGlobalDept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetGlobalDeptResponseGetGlobalDeptResult> GetGlobalDeptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetByUserIDResponseGetByUserIDResult> GetByUserIDAsync(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetByUserEMailID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetByUserEMailIDResponseGetByUserEMailIDResult> GetByUserEMailIDAsync(string EMailID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetBranchDetailByEmployeeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetBranchDetailByEmployeeIDResponseGetBranchDetailByEmployeeIDResult> GetBranchDetailByEmployeeIDAsync(string EMPID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetByUserBr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetByUserBrResponseGetByUserBrResult> GetByUserBrAsync(string UserID, string branchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetByUserIDCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetByUserIDCheckAsync(string UserID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onebank.com.bd/GetGlobalAllBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceUMS.GetGlobalAllBranchResponseGetGlobalAllBranchResult> GetGlobalAllBranchAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetAllUserResponseGetAllUserResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetGlobalEnumResponseGetGlobalEnumResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetGlobalDeptResponseGetGlobalDeptResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetByUserIDResponseGetByUserIDResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetByUserEMailIDResponseGetByUserEMailIDResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetBranchDetailByEmployeeIDResponseGetBranchDetailByEmployeeIDResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetByUserBrResponseGetByUserBrResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://onebank.com.bd/")]
    public partial class GetGlobalAllBranchResponseGetGlobalAllBranchResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface OBLAPPSoapChannel : ServiceReferenceUMS.OBLAPPSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OBLAPPSoapClient : System.ServiceModel.ClientBase<ServiceReferenceUMS.OBLAPPSoap>, ServiceReferenceUMS.OBLAPPSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OBLAPPSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OBLAPPSoapClient.GetBindingForEndpoint(endpointConfiguration), OBLAPPSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OBLAPPSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OBLAPPSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OBLAPPSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OBLAPPSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OBLAPPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetAllUserResponseGetAllUserResult> GetAllUserAsync()
        {
            return base.Channel.GetAllUserAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetEmployeeNameByAsync(string EmployeeID)
        {
            return base.Channel.GetEmployeeNameByAsync(EmployeeID);
        }
        
        public System.Threading.Tasks.Task<long> GetIDbyEmployeeIdAsync(string EmployeeID)
        {
            return base.Channel.GetIDbyEmployeeIdAsync(EmployeeID);
        }
        
        public System.Threading.Tasks.Task<string> GetPreDeptNameByAsync(string EmployeeID)
        {
            return base.Channel.GetPreDeptNameByAsync(EmployeeID);
        }
        
        public System.Threading.Tasks.Task<int> GetPreDeptIdByAsync(string EmployeeID)
        {
            return base.Channel.GetPreDeptIdByAsync(EmployeeID);
        }
        
        public System.Threading.Tasks.Task<int> GetPreBranchIdByAsync(string EmployeeID)
        {
            return base.Channel.GetPreBranchIdByAsync(EmployeeID);
        }
        
        public System.Threading.Tasks.Task<int> GetPreDesigByAsync(string EmployeeID)
        {
            return base.Channel.GetPreDesigByAsync(EmployeeID);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetGlobalEnumResponseGetGlobalEnumResult> GetGlobalEnumAsync()
        {
            return base.Channel.GetGlobalEnumAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetDeptNameByDeptIdAsync(int DeptId)
        {
            return base.Channel.GetDeptNameByDeptIdAsync(DeptId);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetGlobalDeptResponseGetGlobalDeptResult> GetGlobalDeptAsync()
        {
            return base.Channel.GetGlobalDeptAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetByUserIDResponseGetByUserIDResult> GetByUserIDAsync(string UserID)
        {
            return base.Channel.GetByUserIDAsync(UserID);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetByUserEMailIDResponseGetByUserEMailIDResult> GetByUserEMailIDAsync(string EMailID)
        {
            return base.Channel.GetByUserEMailIDAsync(EMailID);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetBranchDetailByEmployeeIDResponseGetBranchDetailByEmployeeIDResult> GetBranchDetailByEmployeeIDAsync(string EMPID)
        {
            return base.Channel.GetBranchDetailByEmployeeIDAsync(EMPID);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetByUserBrResponseGetByUserBrResult> GetByUserBrAsync(string UserID, string branchCode)
        {
            return base.Channel.GetByUserBrAsync(UserID, branchCode);
        }
        
        public System.Threading.Tasks.Task<string> GetByUserIDCheckAsync(string UserID, string password)
        {
            return base.Channel.GetByUserIDCheckAsync(UserID, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceUMS.GetGlobalAllBranchResponseGetGlobalAllBranchResult> GetGlobalAllBranchAsync()
        {
            return base.Channel.GetGlobalAllBranchAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OBLAPPSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OBLAPPSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OBLAPPSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.156.2.85:8084/OBLUserServices/OBLAPP.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OBLAPPSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.156.2.85:8084/OBLUserServices/OBLAPP.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OBLAPPSoap,
            
            OBLAPPSoap12,
        }
    }
}
